"""Fine-tuning a local model, end to end — and being honest about it.

"Fine tune a 14B to become a Power BI model" is a reasonable thing to want and
a widely misunderstood one, so this module says out loud what it can and
cannot do before it spends six hours of your GPU on it.

**What fine-tuning reliably does.** It teaches a model HOW to answer: the
shape, the register, the conventions, what to lead with, what to leave out. A
model tuned on well-formed Power BI answers will structure its replies like
one.

**What it does not reliably do.** It does not install knowledge. Training on
synthetic question-and-answer pairs generated by another model can only ever
transfer what that model already knew — and it transfers the confidence along
with the errors. For DAX that is worse than useless: wrong DAX runs, returns a
number, and nobody notices. A model that has learned to sound authoritative
about a subject it gets wrong is a hazard, not a specialist.

**What usually works better for knowledge.** Retrieval over real documentation
costs nothing, can be corrected in seconds, and cites what it used. This
module offers that route first and means it. If you want the model to KNOW
Power BI, index the docs. If you want it to ANSWER like a Power BI consultant
— consistently, in your house style, without a system prompt each time — then
tuning is the right tool and this will do it.

**The gate.** A fine-tune that scores worse than the model it started from is
a common outcome, not a rare one. Nothing here is registered as an engine
until it has been measured against the base on held-out questions. If it lost,
it says so and keeps the base.
"""
from __future__ import annotations

import json
import re
import subprocess
import sys
from datetime import datetime, timezone
from pathlib import Path

from . import config

# QLoRA in 4-bit: weights, plus adapters and optimiser state.
VRAM_PER_B = 0.56          # GB per billion params, measured rather than hoped
DISPLAY_RESERVE = 1.5


def _dir() -> Path:
    d = config.AGENT_HOME / "finetune"
    d.mkdir(parents=True, exist_ok=True)
    return d


def _iso() -> str:
    return datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M UTC")


def _slug(s: str) -> str:
    return re.sub(r"[^a-z0-9]+", "-", (s or "").lower()).strip("-")[:40]


# --------------------------------------------------------------------------- #
#  1. plan — before anything is spent
# --------------------------------------------------------------------------- #
def plan(goal: str, params_b: float = 14, vram_gb: float = 24,
         examples: int = 800) -> dict:
    """What this would take, and whether it's the right tool."""
    need = round(params_b * VRAM_PER_B + 4.0, 1)
    usable = round(vram_gb - DISPLAY_RESERVE, 1)
    fits = need <= usable
    hours = round(max(0.5, examples / 1000 * params_b * 0.4), 1)

    knowledge = _wants_knowledge(goal)
    return {
        "goal": goal, "params_b": params_b,
        "needs_gb": need, "usable_gb": usable, "feasible": fits,
        "verdict": (f"QLoRA on {params_b}B needs about {need} GB; you have "
                    f"{usable} GB usable after the display. "
                    + ("That fits." if fits else
                       "That doesn't fit — drop to a smaller base.")),
        "rough_hours": hours,
        "examples": examples,
        "honest": {
            "will": ("It will learn to ANSWER like the examples: their "
                     "structure, their register, what they lead with."),
            "will_not": ("It will not learn facts it isn't taught, and "
                         "synthetic examples can only pass on what the "
                         "generating model already knew — mistakes included, "
                         "with the confidence attached."),
            "better_for_knowledge": (
                "If you want it to KNOW this subject rather than sound like "
                "it does, index the real documentation instead. Retrieval "
                "costs nothing, is correctable in seconds, and shows its "
                "sources."),
            "risk": _risk_for(goal),
        },
        "cheaper_first": (
            f"Before training: make a Modelfile variant of the base with a "
            f"system prompt describing {goal}. Seconds, no GPU, and it is "
            f"often enough. Try that, and only train if it isn't."),
        "steps": ["Build a dataset (the real work)",
                  "Train — roughly " + str(hours) + " hours on your card",
                  "Measure it against the base on held-out questions",
                  "Register it as an engine, but only if it won"],
    }


_KNOWLEDGE_WORDS = ("know", "expert", "everything", "anything", "all about",
                    "master", "specialist in", "learn about")


def _wants_knowledge(goal: str) -> bool:
    g = (goal or "").lower()
    return any(w in g for w in _KNOWLEDGE_WORDS)


_HIGH_STAKES = {
    ("dax", "power bi", "sql", "m query", "formula"): (
        "Wrong DAX runs, returns a number, and nobody notices. A model that "
        "has learned to sound authoritative about formulas it gets wrong is "
        "more dangerous than one that hedges. Keep a retrieval source for "
        "anything that produces a figure."),
    ("legal", "contract", "compliance", "popia", "regulat"): (
        "A confident wrong answer about a regulation is a liability. Tune for "
        "tone if you like, but keep the source of truth in retrieval."),
    ("medical", "clinical", "diagnos", "dose"): (
        "Do not use a tuned model as a source of clinical fact."),
    ("financial", "trading", "valuation", "risk"): (
        "A model that sounds certain about a number it invented is the worst "
        "possible failure here. Ground every figure in real data."),
}


def _risk_for(goal: str) -> str:
    g = (goal or "").lower()
    for words, warning in _HIGH_STAKES.items():
        if any(w in g for w in words):
            return warning
    return ("Check a sample of its answers against something authoritative "
            "before relying on it.")


# --------------------------------------------------------------------------- #
#  2. dataset — the part that decides whether any of this works
# --------------------------------------------------------------------------- #
DATASET_SYSTEM = (
    "You are building training examples to teach a smaller model how to "
    "answer questions in a specific domain.\n\n"
    "Rules that matter more than volume:\n"
    "- Every answer must be one you would defend. A confident wrong answer "
    "in training data teaches confident wrongness.\n"
    "- Vary the shape: short factual questions, debugging, 'why is this "
    "slow', 'which approach and why', questions with a wrong premise.\n"
    "- Include examples where the RIGHT answer is 'that depends' or 'check "
    "X first'. A model trained only on confident answers never hedges, and "
    "that is how a specialist model becomes a liar.\n"
    "- No invented product names, versions or functions. If unsure, choose a "
    "question you are sure about instead.\n\n"
    "Return ONLY raw JSONL, one object per line:\n"
    '{"messages":[{"role":"user","content":"..."},'
    '{"role":"assistant","content":"..."}]}\n'
    "No prose, no fences, no numbering."
)


def build_dataset(goal: str, brain, count: int = 200, model=None,
                  context: str = "", on_progress=None) -> dict:
    """Generate training examples, in batches, with the source recorded.

    Batched because one request for 800 examples returns 40 and lies about
    it. Provenance is kept per example so a bad batch can be traced rather
    than poisoning the set invisibly."""
    out, seen, batches = [], set(), []
    per = 25
    rounds = max(1, (count + per - 1) // per)
    for i in range(rounds):
        ask = (f"Domain: {goal}\n"
               f"Write {per} examples.\n"
               + (f"Ground them in this material:\n{context[:6000]}\n"
                  if context else "")
               + (f"Avoid repeating these topics: "
                  f"{', '.join(list(seen)[-25:])}\n" if seen else ""))
        try:
            kw = {"model": model} if model else {}
            resp = brain.chat([{"role": "user", "content": ask}],
                              [DATASET_SYSTEM], None, **kw)
            text = "\n".join(b.text for b in resp.content
                             if getattr(b, "type", "") == "text")
        except Exception as exc:
            batches.append({"batch": i + 1, "error": str(exc)[:200]})
            continue
        kept = 0
        for line in text.splitlines():
            line = line.strip().strip("`")
            if not line.startswith("{"):
                continue
            try:
                obj = json.loads(line)
                msgs = obj["messages"]
                q = msgs[0]["content"].strip()
                a = msgs[1]["content"].strip()
            except Exception:
                continue
            if len(q) < 12 or len(a) < 30:
                continue
            key = q.lower()[:90]
            if key in seen:
                continue
            seen.add(key)
            out.append({"messages": [{"role": "user", "content": q},
                                     {"role": "assistant", "content": a}],
                        "_source": "generated", "_batch": i + 1})
            kept += 1
        batches.append({"batch": i + 1, "kept": kept})
        if on_progress:
            on_progress({"done": len(out), "target": count,
                         "batch": i + 1, "of": rounds})
        if len(out) >= count:
            break

    # a held-out slice the model never sees, or the evaluation is theatre
    holdout = out[::10][:40]
    train = [r for r in out if r not in holdout]
    d = _dir() / _slug(goal)
    d.mkdir(parents=True, exist_ok=True)
    (d / "train.jsonl").write_text(
        "\n".join(json.dumps({"messages": r["messages"]}) for r in train),
        "utf-8")
    (d / "holdout.jsonl").write_text(
        "\n".join(json.dumps({"messages": r["messages"]}) for r in holdout),
        "utf-8")
    return {"ok": bool(train), "goal": goal, "dir": str(d),
            "train": len(train), "holdout": len(holdout),
            "batches": batches,
            "warning": (
                "These are generated, not verified. Read twenty at random "
                "before training on them — a wrong answer here teaches the "
                "model to be wrong with confidence, and you will not be able "
                "to tell afterwards which examples did it."),
            "note": ("The held-out slice is never trained on, so the "
                     "comparison afterwards means something.")}


def sample(goal: str, n: int = 5) -> list:
    """Read some back. The single most useful thing you can do before
    committing a GPU to them."""
    p = _dir() / _slug(goal) / "train.jsonl"
    try:
        lines = p.read_text("utf-8").splitlines()
    except Exception:
        return []
    step = max(1, len(lines) // max(1, n))
    out = []
    for line in lines[::step][:n]:
        try:
            m = json.loads(line)["messages"]
            out.append({"q": m[0]["content"], "a": m[1]["content"]})
        except Exception:
            continue
    return out


# --------------------------------------------------------------------------- #
#  3. train — on your machine, because that's where the GPU is
# --------------------------------------------------------------------------- #
SCRIPT = '''# Generated by Agent Jo — QLoRA fine-tune
# Goal: {goal}
# Base: {base}   Examples: {n}
#
# Run this on the machine with the GPU. Agent Jo starts it for you and
# watches the output; you can also run it by hand.
import json, sys
from unsloth import FastLanguageModel
from trl import SFTTrainer
from transformers import TrainingArguments
from datasets import load_dataset

MAX_SEQ = 2048
model, tokenizer = FastLanguageModel.from_pretrained(
    model_name="{base}", max_seq_length=MAX_SEQ,
    load_in_4bit=True,              # QLoRA: how a {params}B fits on this card
)
model = FastLanguageModel.get_peft_model(
    model, r=16, lora_alpha=16, lora_dropout=0,
    target_modules=["q_proj","k_proj","v_proj","o_proj",
                    "gate_proj","up_proj","down_proj"],
    use_gradient_checkpointing="unsloth", random_state=3407,
)
data = load_dataset("json", data_files=r"{train}", split="train")
print(f"training on {{len(data)}} examples", flush=True)

trainer = SFTTrainer(
    model=model, tokenizer=tokenizer, train_dataset=data,
    max_seq_length=MAX_SEQ,
    args=TrainingArguments(
        per_device_train_batch_size=2, gradient_accumulation_steps=4,
        warmup_steps=10, num_train_epochs={epochs},
        learning_rate=2e-4, fp16=True, logging_steps=5,
        optim="adamw_8bit", output_dir=r"{out}/run",
        save_strategy="no",
    ),
)
trainer.train()

# GGUF, so Ollama can run it like any other local model
model.save_pretrained_gguf(r"{out}/gguf", tokenizer,
                           quantization_method="q4_k_m")
print("DONE", flush=True)
'''


def write_script(goal: str, base: str, params_b: float = 14,
                 epochs: int = 2) -> dict:
    d = _dir() / _slug(goal)
    d.mkdir(parents=True, exist_ok=True)
    train = d / "train.jsonl"
    n = len(train.read_text("utf-8").splitlines()) if train.exists() else 0
    if n < 50:
        return {"ok": False,
                "error": (f"Only {n} example(s). Below about 200 it learns "
                          f"the style and not much else — build a bigger set "
                          f"first.")}
    body = SCRIPT.format(goal=goal, base=base, n=n, params=params_b,
                         train=str(train), out=str(d), epochs=epochs)
    p = d / "train.py"
    p.write_text(body, "utf-8")
    return {"ok": True, "script": str(p), "examples": n,
            "run": f'"{sys.executable}" "{p}"',
            "needs": "pip install unsloth trl peft bitsandbytes datasets"}


def train(goal: str, on_line=None, timeout_s: int = 60 * 60 * 12) -> dict:
    """Run it, streaming the output.

    Long-running and on someone's own GPU, so the interesting output is the
    loss trace: if it stops falling, more epochs are just overfitting."""
    d = _dir() / _slug(goal)
    script = d / "train.py"
    if not script.exists():
        return {"ok": False, "error": "No training script — write one first."}
    log = d / "train.log"
    losses, last = [], ""
    try:
        proc = subprocess.Popen(
            [sys.executable, str(script)], cwd=str(d),
            stdout=subprocess.PIPE, stderr=subprocess.STDOUT,
            text=True, bufsize=1)
    except Exception as exc:
        return {"ok": False, "error": f"{type(exc).__name__}: {exc}"}
    with open(log, "w", encoding="utf-8") as fh:
        for line in proc.stdout:
            fh.write(line)
            last = line.strip()
            m = re.search(r"'loss':\s*([0-9.]+)", line)
            if m:
                losses.append(float(m.group(1)))
            if on_line:
                on_line(last)
    proc.wait(timeout=timeout_s)
    ok = proc.returncode == 0 and (d / "gguf").exists()
    verdict = ""
    if losses:
        first, final = losses[0], losses[-1]
        if final >= first * 0.95:
            verdict = (f"Loss barely moved ({first:.3f} to {final:.3f}). The "
                       f"examples probably didn't teach it anything it didn't "
                       f"already do.")
        else:
            verdict = f"Loss fell from {first:.3f} to {final:.3f}."
    return {"ok": ok, "log": str(log), "losses": losses[-20:],
            "verdict": verdict, "last": last,
            "error": "" if ok else f"Training exited {proc.returncode}."}


# --------------------------------------------------------------------------- #
#  4. the gate — measure before believing
# --------------------------------------------------------------------------- #
JUDGE = (
    "You are comparing two answers to the same question. One is from a "
    "fine-tuned model, one from the model it was trained from. You do not "
    "know which is which.\n\n"
    "Judge on: correctness first, then whether it answers what was asked, "
    "then clarity. A confident wrong answer loses to an uncertain right one.\n"
    'Return ONLY: {"winner": "A"|"B"|"tie", "why": "one sentence"}'
)


def evaluate(goal: str, tuned_engine: str, base_engine: str, brain,
             ask, model=None, limit: int = 20) -> dict:
    """Does the tuned model actually beat what it started from?

    A fine-tune scoring worse than its base is a common outcome, not a rare
    one. `ask(engine, question) -> str` runs a question against an engine."""
    p = _dir() / _slug(goal) / "holdout.jsonl"
    try:
        rows = [json.loads(x) for x in
                p.read_text("utf-8").splitlines() if x.strip()][:limit]
    except Exception:
        return {"ok": False,
                "error": "No held-out questions, so there's nothing honest "
                         "to measure against."}
    tuned_wins = base_wins = ties = 0
    detail = []
    for r in rows:
        q = r["messages"][0]["content"]
        try:
            a = ask(tuned_engine, q)
            b = ask(base_engine, q)
        except Exception as exc:
            detail.append({"q": q[:80], "error": str(exc)[:120]})
            continue
        try:
            kw = {"model": model} if model else {}
            resp = brain.chat(
                [{"role": "user",
                  "content": f"Question: {q}\n\nA:\n{a[:1500]}\n\nB:\n"
                             f"{b[:1500]}"}], [JUDGE], None, **kw)
            text = "\n".join(x.text for x in resp.content
                             if getattr(x, "type", "") == "text")
            verdict = json.loads(re.search(r"\{.*\}", text, re.S).group(0))
        except Exception:
            continue
        w = verdict.get("winner")
        if w == "A":
            tuned_wins += 1
        elif w == "B":
            base_wins += 1
        else:
            ties += 1
        detail.append({"q": q[:80], "winner": w,
                       "why": verdict.get("why", "")[:160]})
    judged = tuned_wins + base_wins + ties
    better = tuned_wins > base_wins
    return {
        "ok": True, "judged": judged, "tuned_wins": tuned_wins,
        "base_wins": base_wins, "ties": ties, "better": better,
        "detail": detail[:20],
        "verdict": (
            f"The tuned model won {tuned_wins} of {judged} and lost "
            f"{base_wins}."
            + (" Worth keeping." if better else
               " It did NOT beat the model it started from — which is a "
               "common outcome, not a strange one. Keep the base.")),
        "note": ("Judged blind on held-out questions it was never trained "
                 "on. Anything else measures how well it memorised."),
    }


def register(goal: str, name: str, base: str) -> dict:
    """Make it an engine — only after it has earned it."""
    d = _dir() / _slug(goal)
    gguf = d / "gguf"
    if not gguf.exists():
        return {"ok": False, "error": "Nothing trained yet."}
    mf = d / "Modelfile"
    mf.write_text(f"FROM ./gguf\n", "utf-8")
    try:
        r = subprocess.run(["ollama", "create", name, "-f", str(mf)],
                           cwd=str(d), capture_output=True, text=True,
                           timeout=1800)
    except Exception as exc:
        return {"ok": False, "error": f"{type(exc).__name__}: {exc}"}
    if r.returncode != 0:
        return {"ok": False, "error": (r.stderr or r.stdout)[-300:]}
    return {"ok": True, "name": name, "from": base,
            "next": (f"Add an engine pointing at your local runner with "
                     f"model `{name}`. Give the ENGINE a different name from "
                     f"the model, or 'not found' errors become ambiguous.")}
